// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1707:識別項不應包含底線", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_ReturnException_WhenEmailIsNotUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:識別項不應包含底線", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_ReturnSuccessResult_WhenEmailIsUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:識別項不應包含底線", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_CallAddOnRepository_WhenEmailIsUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_CallAddOnRepository_WhenEmailIsUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:請考慮對等候的工作呼叫 ConfigureAwait", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_CallAddOnRepository_WhenEmailIsUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:請考慮對等候的工作呼叫 ConfigureAwait", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_NotCallUnitOfWork_WhenEmailIsNotUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:識別項不應包含底線", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_NotCallUnitOfWork_WhenEmailIsNotUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_NotCallUnitOfWork_WhenEmailIsNotUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_ReturnException_WhenEmailIsNotUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1515:Single-line comment should be preceded by blank line", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_ReturnException_WhenEmailIsNotUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1005:Single line comments should begin with single space", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_ReturnSuccessResult_WhenEmailIsUnique~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:請考慮對等候的工作呼叫 ConfigureAwait", Justification = "<暫止>", Scope = "member", Target = "~M:eGathering.Application.UnitTest.Members.Commands.CreateMember.CreateMemberCommandHandlerTests.Handle_Should_ReturnSuccessResult_WhenEmailIsUnique~System.Threading.Tasks.Task")]